let movies = ["24",
	"Ayan",
	"Billa",
	"Biriyani",
	"Chandramukhi",
	"Chinna Thambi",
	"Desingu Raja",
	"Dheena",
	"Enthiran",
	"Engeyum Kadhal",
	"Ethir Neechal",
	"Friends",
	"Jeans",
	"Ghajini",
	"Ghilli",
	"I",
	"Iru Mugan",
	"Kabaali",
	"Kadal",
	"Kadhal Oviyam",
	"Kanchana",
	"Kanda Naal Muthal",
	"Maan Karate",
	"Maattrraan",
	"Mella Thirandhathu Kadhavu",
	"Mouna Ragam",
	"Mounam pesiyadhe",
	"Mozhi",
	"Naanum Rowdy Thaan",
	"Nanban",
	"Nayagan",
	"Oru Kal Oru Kannadi",
	"Oomai Vizhigal",
	"Oru Thalai Ragam",
	"Paiyaa",
	"Punnagai Mannan",
	"Saamy",
	"Saguni",
	"Thani Oruvan",
	"Vaaranam Aayiram"
]

export { movies }